### ISSUE TITLE
No Network message displayed after recent update to 0.2.2

### ISSUE THREAD

**Issue by waynelloyd** [bobo1993324/UDropCabin#15]
I installed the most recent update I could see the directories and new theme but I receive a No Network message after recent update to v0.2.2, I cleared the cache removed and readded the dropbox account but the issue persists

UDropCabinLog file http://paste.ubuntu.com/11830010/

![screenshot20150706_103726609](https://cloud.githubusercontent.com/assets/406940/8519591/a3ebd9fc-23cb-11e5-8380-a288c8b8abe6.png)

**Comment by bobo1993324** [comment]
I am sorry it doesn't work for you. 

I cannot reproduce this easily.
I installed old version. log in and install newer version. It works for me. 

Can you send me the log file located at /home/phablet/.cache/upstart/application-click-com.ubuntu.developer.bobo1993324.udropcabin_uDropCabin_0.2.2.log ?

If you just want it to work, maybe you can try removing directory  /home/phablet/.local/share/com.ubuntu.developer.bobo1993324.udropcabin/ and restart the application.

**Comment by waynelloyd** [comment]
Hi thanks for getting back to me

I tried as you suggested by removing the directory /home/phablet/.local/share/com.ubuntu.developer.bobo1993324.udropcabin/ but the problem is still experienced

Here is the complete contents of log home/phablet/.cache/upstart/application-click-com.ubuntu.developer.bobo1993324.udropcabin_uDropCabin_0.2.2.log

 It seems my original pastebin did not include the entire log
 
http://paste.ubuntu.com/11835819/

**Comment by bobo1993324** [comment]
Thank for you time, I didn't see too much from the log there. It looks like Dropbox is not responding to API to list the directory. There has been a change.

Try this 

https://www.dropbox.com/s/mc22j3dphe02gzx/com.ubuntu.developer.bobo1993324.udropcabin_0.2.2_armhf.click?dl=0

This revert the only api change I have made since last publish and enabled the network logs.

Would you please remove old logs. I shouldn't print token and token secret there. Not anymore.

**Comment by waynelloyd** [comment]
I removed all logs and installed the suggested click package

The same problem is experienced

Please find log contents http://paste.ubuntu.com/11836893

**Comment by waynelloyd** [comment]
I not sure if its helpful but I found errors in the url-dispatcher.log reference uDropCabin

**Comment by bobo1993324** [comment]
Thank you. Are you connecting with 3G network? I am don't have 3G on my BQ, all wifi. 

If that is the case, then NetworkingStatus.online is not working, because no list request is sent and I check NetworkingStatus.online before that.

**Comment by bobo1993324** [comment]
Try https://www.dropbox.com/s/mc22j3dphe02gzx/com.ubuntu.developer.bobo1993324.udropcabin_0.2.2_armhf.click?dl=0 

This use try an error for detecting online status instead of using NetworkingStatus.online

**Comment by Consumology** [comment]
Excellent, I had this issue on bq 4.5 (new installation) and MX4 (update) - no matter if WiFi, LTE or 3G. The above version solves this problem! Thank you!

**Comment by waynelloyd** [comment]
With testing the latest upload I can confirm the problem is fixed Thank you!
